# Generated by Django 5.0.7 on 2025-07-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_login_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='cart_images/')),
            ],
        ),
    ]
