# Generated by Django 5.0.7 on 2025-07-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('pro_img', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.cartitem')),
            ],
        ),
    ]
