# Generated by Django 5.0.7 on 2025-07-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.products')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.login')),
            ],
        ),
    ]
