# Generated by Django 5.0.7 on 2025-08-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_login_dob_login_first_name_login_last_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('products', 'user_email')},
        ),
    ]
