# Generated by Django 5.0.7 on 2025-08-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_favourite_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user_email',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('product', 'user')},
        ),
    ]
