# Generated by Django 5.0.7 on 2025-09-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_products_favourite_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_product_details', to='api.products')),
                ('saved_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_user_details', to='api.login')),
            ],
        ),
    ]
