# Generated by Django 5.0.7 on 2025-09-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_saveitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitems',
            old_name='saved_product_id',
            new_name='saved_product',
        ),
    ]
