# Generated by Django 5.0.7 on 2025-09-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_saved_product_id_saveitems_saved_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitems',
            old_name='saved_product',
            new_name='saved_product_id',
        ),
    ]
