# Generated by Django 5.0.7 on 2025-09-06 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_saved_product_saveitems_saved_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_product_id', to='api.products')),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to='api.login')),
            ],
        ),
    ]
