# Generated by Django 5.0.7 on 2025-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_likeitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
