# Generated by Django 5.0.7 on 2025-09-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_buyitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitems',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
