# Generated by Django 5.0.7 on 2025-09-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_buyitems_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyitems',
            name='rating',
        ),
    ]
