# Generated by Django 5.0.7 on 2025-09-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_buyitems_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitems',
            name='feedback',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_img',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
