# Generated by Django 5.0.7 on 2025-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_buyitems_feedback_alter_products_pro_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitems',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
